server:
  port: 8080
spring:
  application:
    name: API调度系统
  profiles:
    active: dev
  cache:
    cache-names:
      - api
    type: simple
  r2dbc:
    url: r2dbc:mysql://${mysql_host}:3306/api_scheduler?useUnicode=true&characterEncoding=utf8&useSSL=false&allowPublicKeyRetrieval=true&allowMultiQueries=true
    username: root
    password: ${mysql_password}
    pool:
      validation-depth: remote
  mail:
    host: smtp.qq.com
    username: 1829462342@qq.com
    password: ${qqmail_key}
    port: 587
    properties:
      nick: ${spring.application.name}
      default-subject: 您有新的通知了！
logging:
  pattern:
    dateformat: MM-dd HH:mm:ss zzzZZZ

